### ISSUE TITLE
fonts task not ending properly?

### ISSUE THREAD

**Issue by xmlking** [yeoman/generator-webapp#159]
Unlike other tasks `fonts` doesn't seems ending properly. Why `fonts` task not printing `Finished` statement?
This is causing my build task fail. I noticed this behavior after updating my package.json to latest versions ( gulp, gulp-filter, gulp-bower-files ... )

This fails...

``` js
gulp.task('build', ['jshint', 'html', 'images', 'fonts', 'extras'], function () {
    return gulp.src('dist/**/*').pipe($.size({title: 'build', gzip: true}));
});
```

but this works...

``` js
gulp.task('build', ['jshint', 'html', 'images', 'extras'], function () {
    return gulp.src('dist/**/*').pipe($.size({title: 'build', gzip: true}));
});
```

`fonts` task output: (no `Finished` statement in the output)

```
C:\Work\demo>gulp fonts
[16:14:22] Using gulpfile C:\Work\demo\gulpfile.js
[16:14:22] Starting 'fonts'...
```

`styles` task output:

```
C:\Work\demo>gulp styles   
[16:15:26] Using gulpfile C:\Work\demo\gulpfile.js
[16:15:26] Starting 'styles'...
[16:15:29] Finished 'styles' after 2.93 s
```

Environment 

```
  "gulp": "^3.8.1",
  "gulp-filter": "^0.5.0",
  "gulp-flatten": "^0.0.2", 
  "gulp-bower-files": "^0.2.5",
```

``` js
gulp.task('fonts', function () {
  var streamqueue = require('streamqueue');
  return streamqueue({objectMode: true},
      $.bowerFiles(),
      gulp.src('app/fonts/**/*')
    )
    .pipe($.filter('**/*.{eot,svg,ttf,woff}'))
    .pipe($.flatten())
    .pipe(gulp.dest('dist/fonts'));
});
```

Error:

```
undefined:1672
      for (var $__19 = iterable[Symbol.iterator](),
                                                ^
TypeError: Property 'Symbol()' of object  is not a function
    at new Set (eval at <anonymous> (C:\Work\demo\node_modules\gulp-traceur\node_modules\traceur\src\node\traceur.js:24:17), <anonymous>:1672:49)
    at uniqSet (C:\Work\demo\node_modules\gulp-filter\node_modules\multimatch\node_modules\array-union\node_modules\array-uniq\index.js:18:3)
    at module.exports (C:\Work\demo\node_modules\gulp-filter\node_modules\multimatch\node_modules\array-union\index.js:5:9)
    at C:\Work\demo\node_modules\gulp-filter\node_modules\multimatch\index.js:25:10
    at Array.reduce (native)
    at module.exports (C:\Work\demo\node_modules\gulp-filter\node_modules\multimatch\index.js:20:18)
    at Transform._transform (C:\Work\demo\node_modules\gulp-filter\index.js:18:6)
    at Transform._read (C:\Work\demo\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Work\demo\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Work\demo\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:238:10)
```

**Comment by silvenon** [comment]
Closed due to inactivity and nobody else reporting a similar issue.

**Comment by timbog80** [comment]
with the latest build of gulp-webapp on yeoman it looks like this:
```
gulp.task('fonts', function () {
  return gulp.src(require('main-bower-files')({
    filter: '**/*.{eot,svg,ttf,woff,woff2}'
  }).concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});
```
and it still doesnt work
getting this error:
```
gulp serve
[18:49:10] Using gulpfile ~/Sites/yo/gulpfile.js
[18:49:10] Starting 'styles'...
[18:49:10] Starting 'fonts'...
[18:49:10] 'fonts' errored after 2.52 ms
[18:49:10] Error: Cannot find module 'gulp-grep-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Gulp.<anonymous> (/Users/92slavik/Sites/yo/gulpfile.js:60:16)
    at module.exports (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/92slavik/npm-global/lib/node_modules/gulp/bin/gulp.js:129:20
[18:49:10] Finished 'styles' after 469 ms
```
