### ISSUE TITLE
Error when starting HTML

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#258]
Hi there,

I got error when I run `gulp`, and the error show when html is starting. Here the error:

```
[gulp] Starting 'html'...
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.EventEmitter.emit (events.js:74:15)
    at Transform.onerror (/Applications/XAMPP/xamppfiles/htdocs/quranesia-desktop/Site/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.EventEmitter.emit (events.js:95:17)
    at Transform.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/quranesia-desktop/Site/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/quranesia-desktop/Site/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/quranesia-desktop/Site/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)
```

Any thoughts?

**Comment by rizqinizamil** [comment]
UPDATE:
I've updated gulp-useref according to https://github.com/yeoman/generator-gulp-webapp/issues/229 but I still get the same error.

**Comment by sindresorhus** [comment]
Handle the error and see what it says (I know it's stupid that Node streams doesn't show the error until you do).

https://www.google.no/search?q=gulp+handle+error

**Comment by rizqinizamil** [comment]
Turns out I have bad plugin path. Sorry, it's my false. Issue closed.
