### ISSUE TITLE
Failure on 'yo gulp-webapp'

### ISSUE THREAD

**Issue by doublemarked** [yeoman/generator-webapp#282]
This failure happens when trying to generate a new app, using version 0.3.0:

```
Scallop-2$ yo gulp-webapp
/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/yeoman-generator/lib/base.js:444
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:330:20)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:66:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:53:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:155:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by doublemarked** [comment]
Hmm, sorry - I upgraded yo and the problem went away.

**Comment by muminoff** [comment]
:+1: 
I had the same problem and now ok.
