### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Mantrama** [yeoman/generator-webapp#283]
Hi There,
After many time trying still got error after run `yo gulp-webapp`.
3rd of options are selected: SASS, Bootstrap, Modernizr.
## this is what I see in CMD in OS: Windows 8.1.

gulp-sass@1.3.3 node_modules\gulp-sass
├── clone@0.1.19
├── map-stream@0.1.0
├── gulp-util@3.0.3 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, array-uniq@1.0.2, replace-ext@0.0.1, lodash.reevaluate@3.0.1, lodash.reescape@3.0.1, lodash.reinterpolate@3.0.1, minimist@1.1.0, chalk@0.5.1, vinyl@0.4.6, lodash.template@3.3.0, through2@0.6.3, dateformat@1.0.11, multipipe@0.1.2)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── node-sass@2.0.1 (get-stdin@4.0.1, object-assign@2.0.0, replace-ext@0.0.1, cross-spawn@0.2.6, nan@1.6.2, semver@4.3.0, mkdirp@0.5.0, chalk@0.5.1, shelljs@0.3.0, meow@3.0.0, npmconf@2.1.1, gaze@0.5.1, sass-graph@1.0.3, mocha@2.1.0, request@2.53.0)

module.js:340
    throw err;
          ^
Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Amir\AppData\Roaming\npm\node_modules\generator-mocha\generators\app\index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/27283025/yeoman-angular-generator-error

**Comment by Mantrama** [comment]
Thanks,
Updating Node & npm plus all the global packages through 'npm update' command resolve it.
