### ISSUE TITLE
After adding Jade recipe, error on HTML task

### ISSUE THREAD

**Issue by markpalfreeman** [yeoman/generator-webapp#291]
I've swapped out Jade as shown in the recipe here: https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/jade.md

I can run the watch task just fine, but upon build, the 'html' gulp task produces the following error:

Starting 'html'...
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Transform.emit (events.js:87:13)
    at Transform.onerror (ROOT/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:107:17)
    at Transform.<anonymous> (ROOT/node_modules/gulp-useref/index.js:76:42)
    at Array.forEach (native)
    at Transform.<anonymous> (ROOT/node_modules/gulp-useref/index.js:66:35)
    at Array.forEach (native)
    at Transform.<anonymous> (ROOT/node_modules/gulp-useref/index.js:44:36)
    at Array.forEach (native)

Any ideas of what's wrong here?

**Comment by silvenon** [comment]
Which version of generator-gulp-webapp are you running?

**Comment by sindresorhus** [comment]
Attach and error handler to see the actual error, and share it.

**Comment by markpalfreeman** [comment]
Ah, it was the version! I didn't go through the generator process correctly, so it defaulted to an older version. Updating my gulpfile and package.json did the trick.
