### ISSUE TITLE
 Cannot find module 'orchestrator'

### ISSUE THREAD

**Issue by azumbrunnen** [yeoman/generator-webapp#318]
Did everything as described, got this:

$ gulp
module.js:338
    throw err;
          ^
Error: Cannot find module 'orchestrator'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (./node_modules/gulp/index.js:4:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by sindresorhus** [comment]
You seem to have not run `npm install` or have suffered an npm install corruption. Upgrade to latest Node.js and npm (`$ npm install -g npm`) and reinstall.

npm support: https://github.com/npm/npm/issues
