### ISSUE TITLE
Getting font error on clean install of gulp-webapp

### ISSUE THREAD

**Issue by timbog80** [yeoman/generator-webapp#322]
with the latest build of gulp-webapp on yeoman it looks like this:

```
gulp.task('fonts', function () {
  return gulp.src(require('main-bower-files')({
    filter: '**/*.{eot,svg,ttf,woff,woff2}'
  }).concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});
```

and it still doesnt work
getting this error:

```
gulp serve
[18:49:10] Using gulpfile ~/Sites/yo/gulpfile.js
[18:49:10] Starting 'styles'...
[18:49:10] Starting 'fonts'...
[18:49:10] 'fonts' errored after 2.52 ms
[18:49:10] Error: Cannot find module 'gulp-grep-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Gulp.<anonymous> (/Users/92slavik/Sites/yo/gulpfile.js:60:16)
    at module.exports (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/92slavik/npm-global/lib/node_modules/gulp/bin/gulp.js:129:20
[18:49:10] Finished 'styles' after 469 ms
```

**Comment by sindresorhus** [comment]
> [18:49:10] Error: **Cannot find module 'gulp-grep-stream'**

**Comment by timbog80** [comment]
ummm so how do i fix this?

**Comment by timbog80** [comment]
ok i think i got that. now im getting this:
```
gulp serve
[19:25:02] Using gulpfile ~/Sites/yo/gulpfile.js
[19:25:02] Starting 'styles'...
[19:25:02] Starting 'fonts'...
[19:25:03] 'fonts' errored after 82 ms
[19:25:03] Error: Bower components directory does not exist at /Users/92slavik/Sites/yo/bower_components
    at Error (native)
    at module.exports (/Users/92slavik/Sites/yo/node_modules/main-bower-files/lib/index.js:76:71)
    at Gulp.<anonymous> (/Users/92slavik/Sites/yo/gulpfile.js:54:46)
    at module.exports (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/92slavik/Sites/yo/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/92slavik/npm-global/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
[19:25:03] Finished 'styles' after 483 ms
```

**Comment by timbog80** [comment]
got it thanks :)
