### ISSUE TITLE
'images' errored

### ISSUE THREAD

**Issue by tulsadome** [yeoman/generator-webapp#371]
When running gulp to build production app i get this error. I've tried running npm install and running yo gulp-webapp in the directory again but I can't seem to get it to work.

[16:33:58] Requiring external module babel-core/register
[16:34:11] Using gulpfile ~/git/bobbi-bortolussi/gulpfile.babel.js
[16:34:11] Starting 'clean'...
[16:34:11] Finished 'clean' after 51 ms
[16:34:11] Starting 'default'...
[16:34:11] Starting 'lint'...
[16:34:20] Starting 'styles'...
[16:34:29] Starting 'images'...
[16:34:36] 'images' errored after 6.61 s
[16:34:36] Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:20:23)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:47:14)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js](/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/babel-core/lib/api/register/node.js:214:7)
[16:34:36] Finished 'default' after 24 s
[16:34:36] Finished 'lint' after 25 s
[16:34:37] Finished 'styles' after 17 s

**Comment by tulsadome** [comment]
Ok so I got past that issue with npm install --save-dev gulp-imagemin but now I'm getting this

[16:46:51] Requiring external module babel-core/register
[16:47:01] Using gulpfile ~/git/bobbi-bortolussi/gulpfile.babel.js
[16:47:01] Starting 'clean'...
[16:47:01] Finished 'clean' after 30 ms
[16:47:01] Starting 'default'...
[16:47:01] Starting 'lint'...
[16:47:07] Starting 'styles'...
[16:47:14] Starting 'images'...
[16:47:21] Starting 'fonts'...
[16:47:22] Starting 'extras'...
[16:47:22] Finished 'default' after 21 s
[16:47:23] Finished 'lint' after 22 s
[16:47:23] Finished 'extras' after 454 ms
[16:47:23] Finished 'fonts' after 1.43 s
[16:47:23] Finished 'styles' after 16 s
[16:47:23] Starting 'html'...
[16:47:27] 'html' errored after 3.76 s
[16:47:27] Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/gulp-useref/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:20:23)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/gulp-useref/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/unique-stream/node_modules/through2-filter/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:47:14)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tylerbarnes/git/bobbi-bortolussi/node_modules/babel-core/lib/api/register/node.js:214:7)
[16:47:27] Finished 'images' after 13 s


I'm assuming I need to reinstall gulp-useref to get past this. Why doesn't it just run properly? Is there something wrong with the generator or am I doing something wrong?

**Comment by tulsadome** [comment]
running npm install --save-dev gulp-imagemin and then npm install --save-dev gulp-useref fixed the issue but does anyone know what causes this issue?

**Comment by arthurvr** [comment]
> running npm install --save-dev gulp-imagemin and then npm install --save-dev gulp-useref fixed the issue but does anyone know what causes this issue?

Those dependencies are in the scaffolded package.json so you probably just had an installation problem. I'm glad it's fixed now :)
