### ISSUE TITLE
Optipng errors during init

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp#399]
When I do a `yo gulp-webapp` I see the following:

```
> optipng-bin@3.0.2 postinstall /Users/greg/SpiderOak Hive/Work/Other/blarg/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ⚠ Command failed: /bin/sh -c /Users/greg/SpiderOak Hive/Work/Other/blarg/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor/optipng --version
/bin/sh: /Users/greg/SpiderOak: No such file or directory

  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --with-system-zlib --prefix="/Users/greg/SpiderOak Hive/Work/Other/blarg/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" --bindir="/Users/greg/SpiderOak Hive/Work/Other/blarg/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/vendor" && make install
Command failed: /bin/sh -c make install
pngrtran.c:97:1: warning: unused function 'png_rtran_ok' [-Wunused-function]
png_rtran_ok(png_structrp png_ptr, int need_IHDR)
^
1 warning generated.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngpread.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpng.a(pngwtran.o) has no symbols
pngxmem.c:37:32: warning: comparison of constant 2305843009213693951 with expression of type 'png_uint_32' (aka 'unsigned int') is always false [-Wtautological-constant-out-of-range-compare]
   if (row_size == 0 || height > (pngx_alloc_size_t)(-1) / sizeof(png_bytep))
                        ~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libpngxtern.a(pngxio.o) has no symbols
osys.c:525:25: error: no member named 'st_atim' in 'struct stat'
        times[0] = sbuf.st_atim;
                   ~~~~ ^
osys.c:526:25: error: no member named 'st_mtim' in 'struct stat'
        times[1] = sbuf.st_mtim;
                   ~~~~ ^
osys.c:527:13: warning: implicit declaration of function 'utimensat' is invalid in C99 [-Wimplicit-function-declaration]
        if (utimensat(AT_FDCWD, dest_path, times, 0) != 0)
            ^
1 warning and 2 errors generated.
make[1]: *** [osys.o] Error 1
make: *** [install] Error 2

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

Any ideas what went wrong beyond optipng being broken?

**Comment by gregmajor** [comment]
Using [homebrew](http://www.brew.sh) to install optipng seems to make everything happy.

**Comment by alferov** [comment]
@gregmajor, this is known [optipng-bin issue](https://github.com/imagemin/optipng-bin/issues/58). It's not related to `generator-gulp-webapp`.

**Comment by silvenon** [comment]
We'll keep this open until that issue is resolved. Too bad :confused:

**Comment by silvenon** [comment]
It's resolved.
