### ISSUE TITLE
Running Run yo gulp-webapp scaffolding fails

### ISSUE THREAD

**Issue by mkoller** [yeoman/generator-webapp#408]
Running yo gulp-webapp fails at bower jquery

```
bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery.git#~2.1.1
bower jquery#~2.1.1            resolve git://github.com/jquery/jquery.git#~2.1.1
bower modernizr#~2.8.1      not-cached git://github.com/Modernizr/Modernizr.git#~2.8.1
bower modernizr#~2.8.1         resolve git://github.com/Modernizr/Modernizr.git#~2.8.1
bower jquery#~2.1.1            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Operation timed out
bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery.git#~2.1.1
bower jquery#~2.1.1            resolve git://github.com/jquery/jquery.git#~2.1.1
bower modernizr#~2.8.1      not-cached git://github.com/Modernizr/Modernizr.git#~2.8.1
bower modernizr#~2.8.1         resolve git://github.com/Modernizr/Modernizr.git#~2.8.1
bower chai#*                not-cached git://github.com/chaijs/chai.git#*
bower chai#*                   resolve git://github.com/chaijs/chai.git#*
bower mocha#*               not-cached git://github.com/mochajs/mocha.git#*
bower mocha#*                  resolve git://github.com/mochajs/mocha.git#*
bower jquery#~2.1.1            ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.131]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Operation timed out
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: jquery is not installed. Try running `bower install`.
    at /usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/wiredep.js:30:56
    at /usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/lib/detect-dependencies.js:145:29
    at forOwn (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.forEach (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/node_modules/lodash/dist/lodash.js:3303:9)
    at detectDependencies (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/wiredep/wiredep.js:70:39)
    at module.exports.generators.Base.extend.end (/usr/local/lib/node_modules/generator-gulp-webapp/app/index.js:304:5)
    at /usr/local/lib/node_modules/generator-gulp-webapp/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:374:17)

```

After that fails, I tried running `bower install` 
and got the following message

```
bower modernizr#~2.8.1      not-cached git://github.com/Modernizr/Modernizr.git#~2.8.1
bower modernizr#~2.8.1         resolve git://github.com/Modernizr/Modernizr.git#~2.8.1
bower jquery#~2.1.1         not-cached git://github.com/jquery/jquery.git#~2.1.1
bower jquery#~2.1.1            resolve git://github.com/jquery/jquery.git#~2.1.1
bower modernizr#~2.8.1         ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Modernizr/Modernizr.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.128]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=Operation timed out
```

**Comment by silvenon** [comment]
This is a internet connection or a firewall issue, like the output says. eschnou/ardrone-webflight#49 might help.
