### ISSUE TITLE
Error: Cannot find module 'yeoman-environment'

### ISSUE THREAD

**Issue by Webbrother** [yeoman/generator-webapp#409]
1. latest node.js (v 4.2.1)
2. latest npm (v 3.3.8)
3. latest yeoman
4. latest generator-gulp-webapp

when I do: yo gulp-webapp

I get:

```
Error: Cannot find module 'yeoman-environment'
at Function.Module._resolveFilename (module.js:337:15)
at Function.Module._load (module.js:287:25)
at Module.require (module.js:366:17)
at require (module.js:385:17)
at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\generator-gulp-webapp\node_modules\yeoman-generator\index.js:6:19)
at Module._compile (module.js:435:26)
at Object.Module._extensions..js (module.js:442:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:311:12)
at Module.require (module.js:366:17)
at require (module.js:385:17)
```

**Comment by kevva** [comment]
> 3. latest yeoman

Install `yo` instead of `yeoman`.

**Comment by kevva** [comment]
This is most likely a `npm` issue. I'd try reinstalling the generator.
