### ISSUE TITLE
Error: Cannot find module 'yeoman-environment'

### ISSUE THREAD

**Issue by philipmadeley** [yeoman/generator-webapp#420]
I have reviewed the other issue and tried reinstalling the generators but nothing can get past this error.  `yo gulp-webapp` was working perfectly until today. 

latest node (v 5.0.0)
latest npm (v 3.4.0)
latest yeoman
latest generator-gulp-webapp

`module.js:339
    throw err;
    ^
Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-gulp-webapp/node_modules/generator-mocha/node_modules/yeoman-generator/index.js:6:19)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
`

**Comment by sindresorhus** [comment]
This is not the place for npm install support. Try: https://github.com/npm/npm/issues
