### ISSUE TITLE
Cannot find module 'escape-string-regexp'

### ISSUE THREAD

**Issue by deangibson89** [yeoman/generator-webapp#423]
After following the 'Getting started' guide and running yo gulp-webapp I get the following error:

module.js:339
    throw err;
    ^

Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/chalk/index.js:2:26)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Deans-Air:deangibson deang$

**Comment by sindresorhus** [comment]
This is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`. Use the [npm issue tracker](https://github.com/npm/npm/issues) for support.
