### ISSUE TITLE
 'scripts' errored after 1.9 ms

### ISSUE THREAD

**Issue by simplecooler** [yeoman/generator-webapp#439]
I install the generator on the ubuntu and when I run the 'gulp serve',it throw errors
[09:53:49] Requiring external module babel-core/register
[09:53:49] Using gulpfile ~/github/Max/gulpfile.babel.js
[09:53:49] Starting 'styles'...
[09:53:50] Starting 'scripts'...
[09:53:50] 'scripts' errored after 1.9 ms
[09:53:50] TypeError: $.plumber is not a function
    at Gulp.<anonymous> (gulpfile.babel.js:22:13)
    at module.exports (/home/szm/github/Max/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/szm/github/Max/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/szm/github/Max/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/szm/github/Max/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
[09:53:50] Finished 'styles' after 271 ms

**Comment by silvenon** [comment]
I'm guessing you had Sass off, so gulp-plumber was missing. Fix released in [v1.1.1](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.1.1).
