### ISSUE TITLE
I just need some help

### ISSUE THREAD

**Issue by tdopires** [yeoman/generator-webapp#490]
Hi, I've just installed the generator-webapp and I was very excited in getting some stuff done.
But it seems not to work for me :cry: 
In case that the problem is my fault (most of the cases), I already ask for your forgiveness...

Please, take a look at the error messages and try helping me out:

```
$ gulp serve
[12:16:26] Requiring external module babel-core/register
[12:16:27] Using gulpfile ~/Projects/portfolio/gulpfile.babel.js
[12:16:27] Starting 'styles'...
[12:16:27] Starting 'scripts'...
[12:16:27] Starting 'fonts'...

/Users/tdopires/Projects/portfolio/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/Users/tdopires/Projects/portfolio/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DestroyableTransform.logError (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:178:17)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:74:26)
    at TransformState.afterTransform (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at errorM (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:133:14)
    at DestroyableTransform._transform (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:161:16)
    at DestroyableTransform.Transform._read (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_writable.js:313:64)
```

```
$ gulp
[12:16:17] Requiring external module babel-core/register
[12:16:18] Using gulpfile ~/Projects/portfolio/gulpfile.babel.js
[12:16:18] Starting 'clean'...
[12:16:18] Finished 'clean' after 2.62 ms
[12:16:18] Starting 'default'...
[12:16:18] Starting 'lint'...
[12:16:18] Starting 'styles'...
[12:16:18] Starting 'scripts'...
[12:16:18] Starting 'images'...
[12:16:19] Starting 'fonts'...
[12:16:19] Starting 'extras'...
[12:16:19] Finished 'default' after 820 ms
[12:16:19] Finished 'images' after 282 ms
[12:16:19] Finished 'lint' after 876 ms

/Users/tdopires/Projects/portfolio/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
    at new PluginError (/Users/tdopires/Projects/portfolio/node_modules/gulp-util/lib/PluginError.js:73:28)
    at DestroyableTransform.logError (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:178:17)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:74:26)
    at TransformState.afterTransform (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at errorM (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:133:14)
    at DestroyableTransform._transform (/Users/tdopires/Projects/portfolio/node_modules/gulp-sass/index.js:161:16)
    at DestroyableTransform.Transform._read (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:95:17)
    at readableAddChunk (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (/Users/tdopires/Projects/portfolio/node_modules/readable-stream/lib/_stream_readable.js:157:10)
```

**Comment by tdopires** [comment]
I'm trying another 
`npm install --global generator-webapp`
maybe...

**Comment by tdopires** [comment]
I've updated all things and now it's working. YAY! :+1:  

Sorry about opening an issue just for that.
My bad. :disappointed:

**Comment by danmv** [comment]
how did you update all things? I am running into the same error. 
I am new to this and don't know what are all the commands I need to execute to update all things. 
Thanks

**Comment by tdopires** [comment]
Are you running which platform? If you are on Mac OS, be careful with some issues around installing node & npm with homebrew, it's quite common.

I don't remember well how I got out of this, but try [following this](http://stackoverflow.com/a/6237400)

As far as I remember, it was something very simple like:
`$ npm install -g npm`
and after that 
`$ npm update`

**Comment by silvenon** [comment]
@danmv it's coming from Sass, apparently, so you should dig there if your error message has the same stack trace.
