### ISSUE TITLE
Error: Cannot find module 'browserify'

### ISSUE THREAD

**Issue by iholub** [yeoman/generator-webapp#524]
I changed the code according to Recipe https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/browserify.md

and have error Cannot find module 'browserify'.

gulp serve
(node:2292) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
module.js:442
    throw err;
    ^

Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (gulpfile.js:7:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

node -v
v6.2.0

**Comment by oskarrough** [comment]
Looks like the install line in the recipe you linked is missing browserify.

Try

```
npm install browserify --save
gulp serve
```

**Comment by silvenon** [comment]
I updated the recipe and fixed some things, it should work properly now. Let me know if you have any more problems with it.
