### ISSUE TITLE
 Unexpected token

### ISSUE THREAD

**Issue by chanakairugal** [yeoman/generator-webapp#528]
Guys, im really new at gulp and yo thing. so need to clear this out. every time i try to run gulp command in cmd its gives me this huge error msg on gulpfile.js file. but this file from generator so i can tel u i didnt change it at all. can u help me with this issue

```
gulp.task('styles', () => {
                     ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at execute (C:\Users\Adobe Test CC\AppData\Roaming\npm\node_modules\gulp-cli
\lib\versioned\^3.7.0\index.js:24:18)
    at Liftoff.handleArguments (C:\Users\Adobe Test CC\AppData\Roaming\npm\node_
modules\gulp-cli\index.js:150:63)
    at Liftoff.<anonymous> (C:\Users\Adobe Test CC\AppData\Roaming\npm\node_modu
les\gulp-cli\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\Users\Adobe Test CC\AppData\Roaming\npm\node_modules\g
ulp-cli\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\Adobe Test CC\AppData\Roaming\npm\node_modu
les\gulp-cli\node_modules\liftoff\index.js:185:9)
```

**Comment by neilhem** [comment]
hi, what's your nodejs version? Seems like you have installed version lower than 4

**Comment by chanakairugal** [comment]
Thanks @neilhem, but after i did my node update its gives me this error :(

```
[08:25:37] Error: Missing binding G:\Workspaces\my-webapp\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64-46\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 4.x

Found bindings for the following environments:
  - Windows 32-bit with Node 0.10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (G:\Workspaces\my-webapp\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:14:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (G:\Workspaces\my-webapp\node_modules\gulp-sass\index.js:187:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by chanakairugal** [comment]
Hey,  I did resolve this by running after npm rebuild node-sass :D Thanks a lot :dancer:  :+1:

**Comment by silvenon** [comment]
Yeah, node-sass is built with the current version of Node, so you need to rebuild it if you update Node.
