### ISSUE TITLE
Getting unexpected token error running gulp serve

### ISSUE THREAD

**Issue by mcastre** [yeoman/generator-webapp#548]
I just installed a fresh version of the webapp generator, and I tried to run `gulp serve` and it gave me a syntax error: 

```
gulp.task('styles', () => {
                     ^
SyntaxError: Unexpected token )
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/martincastre/.npm-packages/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/martincastre/.npm-packages/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/martincastre/.npm-packages/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

I have tried running `npm install` and havent changed anything to the file structure or code. Is there something else that needs to be done that I didnt see in the documentation?  

Thanks!

**Comment by neilhem** [comment]
Update node to version 4 or higher and reinstall depedencies. Dup #528

**Comment by silvenon** [comment]
Lower versions don't support arrow functions and other ES2015 features. You should've gotten an error when installing generator-webapp that your Node version isn't high enough, as specified in our [`package.json`](https://github.com/yeoman/generator-webapp/blob/12c98e9ea046bba738507cd207ed3eac120ef4b6/package.json#L10). Perhaps you missed it?

**Comment by mcastre** [comment]
awesome, thanks!
