### ISSUE TITLE
'gulp' exec in clean, yo-installed gulp-webapp scaffold fails at " throw er; // Unhandled 'error' event"

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp#568]
after clean-installing a yo/gulp scaffold

```
yo gulp-webapp --skip-cache --skip-welcome-message --babel
```

with

```
yo --version
    1.8.5
gulp --version
    [17:43:21] Requiring external module babel-register
    [17:43:21] CLI version 3.9.1
    [17:43:21] Local version 3.9.1
```

so that

```
tree -L 1
    .
    ├── app
    ├── bower_components
    ├── bower.json
    ├── gulpfile.babel.js
    ├── node_modules
    ├── package.json
    └── test
```

On exec of

```
gulp
```

in the clean-installed project, it fails with

```
[16:55:43] Requiring external module babel-register
[16:55:44] Using gulpfile /home/www/gulpfile.babel.js
[16:55:44] Starting 'clean'...
[16:55:44] Finished 'clean' after 13 ms
[16:55:44] Starting 'default'...
[16:55:44] Starting 'lint'...
[16:55:44] Starting 'styles'...
[16:55:45] Starting 'scripts'...
[16:55:45] Starting 'images'...
[16:55:45] Starting 'fonts'...
[16:55:45] Starting 'extras'...
[16:55:45] Finished 'default' after 753 ms
[16:55:45] Finished 'images' after 251 ms
[16:55:45] Finished 'fonts' after 28 ms
[16:55:45] Finished 'lint' after 857 ms
[16:55:45] Finished 'styles' after 757 ms
[16:55:45] Finished 'scripts' after 494 ms
[16:55:45] Starting 'html'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/home/www/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
```

**Comment by silvenon** [comment]
*_a month later_* 😓 

Did you find why you were receiving that error? It looks like you had a syntax error in your JS, so UglifyJS was crashing.
