### ISSUE TITLE
The "gulp serve" command will crash when there is an empty .scss file.

### ISSUE THREAD

**Issue by maartenpaauw** [yeoman/generator-webapp#584]
Hello,

Today I found out the command "gulp serve" will crash, when there is an empty .scss file in the styles directory, with the following error: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:284:9)
    at Function.Buffer.from (buffer.js:116:10)
    at new Buffer (buffer.js:95:17)
    at DestroyableTransform._transform (/Users/USER/PROJECT/node_modules/wiredep/wiredep.js:136:23)
    at DestroyableTransform.Transform._read (/Users/USER/PROJECT/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/USER/PROJECT/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/USER/PROJECT/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/USER/PROJECT/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/USER/PROJECT/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/USER/PROJECT/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

I think this problem could be solved with a check (if the .scss file is not empty) within the "gulp wiredep" command.

Found this filter function at: 
https://gist.github.com/thomasmb/906302bc9519be8abed5#file-gulpfile-js-L16
```
.pipe($.filter(function(a){ return a.stat && a.stat.size }))
```
Is this a suitable solution? If so, then I will submit a pull-request.

Greetings,

Maarten

**Comment by Karadjordje** [comment]
@m44rt3np44uw 
Hi Maarten I have the same problem. Is there a way around this so I can continue to work until they update it.

**Comment by maartenpaauw** [comment]
@Karadjordje yes there is.

First step is to install gulp-filter via. 

```
npm install gulp-filter --save-dev
```

Add the following code between this two lines: https://github.com/yeoman/generator-webapp/blob/master/app/templates/gulpfile.js#L179-L180

```
.pipe($.filter(function(a){ return a.stat && a.stat.size }))
```

**Comment by silvenon** [comment]
Hey, thanks for reporting this. I will release a patch version today and let you know when it's out.

**Comment by silvenon** [comment]
[v2.3.1](https://github.com/yeoman/generator-webapp/releases/tag/v2.3.1) released.

**Comment by maartenpaauw** [comment]
@silvenon Thanks a lot!
