### ISSUE TITLE
Error gulp serve

### ISSUE THREAD

**Issue by iamchathu** [yeoman/generator-webapp#595]
I get an error 

'TypeError: browserSync is not a function'

**Comment by acivan** [comment]
/Users/Ivan/website/gulpfile.js:90
    browserSync({
    ^

TypeError: browserSync is not a function
    at runSequence (/Users/Ivan/website/gulpfile.js:90:5)
    at finish (/Users/Ivan/website/node_modules/run-sequence/index.js:60:5)
    at runNextSet (/Users/Ivan/website/node_modules/run-sequence/index.js:88:5)
    at Gulp.onTaskEnd (/Users/Ivan/website/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Ivan/website/node_modules/orchestrator/index.js:264:8)
    at /Users/Ivan/website/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Ivan/website/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/Ivan/website/node_modules/orchestrator/lib/runTask.js:52:4

**Comment by silvenon** [comment]
[v2.3.2](https://github.com/yeoman/generator-webapp/releases/tag/v2.3.2) released. Sorry about that. 😅

**Comment by neilhem** [comment]
Dup #594
