### ISSUE TITLE
gulp-rsync recipe throws error

### ISSUE THREAD

**Issue by martisj** [yeoman/generator-webapp#598]
I'm getting this error when trying to deploy with rsync according to the [recipe](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/rsync-deploy.md).

```
[13:09:07] gulp-rsync: Starting rsync to {....}@{.....}:{...}/www...
[13:09:07] gulp-rsync: /bin/sh: -c: line 0: syntax error near unexpected token `('
[13:09:07] gulp-rsync: /bin/sh: -c: line 0: `rsync -Rv --progress ... {lots of files}
```
and then this at the bottom
```
[13:56:00] gulp-rsync:  [13:56:00] 'deploy' errored after 115 ms
[13:56:00] Error in plugin 'gulp-rsync'
Message:
    Error: rsync exited with code 2
    at ChildProcess.<anonymous> (/Users/msjastad/Projects/mcdonalds/homestyle/node_modules/gulp-rsync/rsync.js:110:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
[13:56:00] gulp-rsync: Completed rsync.
```

I know rsync is hardly the best option for deployment, in this case I just gotta' work with what I got 😄 
Any thoughts would be 🦄  🌈  Thanks.

**Comment by neilhem** [comment]
Hi, have you tried `npm rebuild`?

**Comment by martisj** [comment]
@neilhem snap! That worked. Hmmm that's interesting. What made you think that was the issue?

**Comment by silvenon** [comment]
`npm rebuild` rebuilds dependencies, which is useful for those who contain C/C++ (your first code block hinted that). Usually when you compile a C/C++ dependency with one Node version, it won't work on another.
