### ISSUE TITLE
throw er; // Unhandled 'error' event at new JS_Parse_Error

### ISSUE THREAD

**Issue by clabnet** [yeoman/generator-webapp#619]
```
node -v && npm -v && bower -v && gulp -v
v6.7.0
3.10.8
1.8.0
[22:15:12] Requiring external module babel-register
[22:15:12] CLI version 1.2.2
[22:15:12] Local version 3.9.1

gulp-uglify
1.5.4

```
Using generator-webapp@2.3.2, without any modify at your code.

**After `yo webapp --no-babel`, when I run  `gulp build` I have this error:**

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (D:\gulp-workflow\generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2915:7)
```

**Comment by gkobilansky** [comment]
I was having the same problem. After a lot of head scratching, it looks like gulp-useref isn't playing nice with gulp-if.

Changing the if wildcards ('*.js') in the html task seems to resolve it for me.

```
.pipe($.if('**/*.js', $.uglify())
//Instead of: .pipe($.if('*.js', $.uglify())

.pipe($.if('**/*.css', $.csso()))
//Instead of: .pipe($.if('*.css', $.csso()))

.pipe($.if('**/*.html', $.htmlmin({collapseWhitespace: true})))
//instead of: .pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
```

**Comment by silvenon** [comment]
@clabnet thanks for listing all the relevant versions! Unfortunately I was not able to reproduce this error. Does this happen on a fresh install? Did you try @gkobilansky's solution?

To me it looks like you have invalid JavaScript somewhere. Usually Babel would catch it in development, but you built your app without it. Does `gulp lint` pass?

**Comment by feesh** [comment]
Hi there! Can confirm, I ran into the same issue from a fresh install this weekend. I was able to fix it using a similar approach to @gkobilansky that I found here: https://github.com/robrich/gulp-if/issues/70

**Comment by silvenon** [comment]
@feesh thanks! Could you please check if the `b` in `/\.css$/b` is required for the fix to work?

**Comment by clabnet** [comment]
Sorry, on my environment this not running. The same issue of start of thread, **also using babel**.

```
node -v && npm -v && bower -v && gulp -v

v6.7.0
3.10.8
1.8.0
[22:31:26] Requiring external module babel-register
[22:31:26] CLI version 1.2.2
[22:31:26] Local version 3.9.1

```
```

[22:35:11] Starting 'html'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymo
us>:1534:18)
    at js_error (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:1
1)
    at croak (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:209
7:9)
    at unexpected (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103
:9)
    at expr_atom (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2630:
9)
    at maybe_unary (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:279
2:19)
    at expr_ops (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2827:2
4)
    at maybe_conditional (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymou
s>:2832:20)
    at maybe_assign (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:28
56:20)
    at expression (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2875
:20)
    at simple_statement (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous
>:2314:55)
    at eval (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (D:\casavacanzeposeidone.it\casavacanze-new-generator-webapp\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:29
15:7)




```

**Comment by silvenon** [comment]
@clabnet we applied some additional fixes in the meantime, could you try [this](https://github.com/yeoman/generator-webapp/blob/4c0513db7c9375a065d035ee51db987f5b9423cd/app/templates/gulpfile.js#L67-L69)?

**Comment by clabnet** [comment]
Thanks for your response.
      
      Same issue.
    
    I have downloaded now (2 feb 2017 @ 20:48 +1GMT) with this command:
      
    npm install --global yo gulp-cli bower generator-webapp

    These the versions in use:
      
      Yeoman Doctor
        Running sanity checks on your system
        
        √ Global configuration file is valid
        √ NODE_PATH matches the npm root
        √ Node.js version
        √ No .bowerrc file in home directory
        √ No .yo-rc.json file in home directory
        √ npm version
        
        Everything looks all right!
        C:\Program Files\nodejs
        +-- bower@1.8.0
        +-- generator-webapp@2.4.0
        | `-- yeoman-generator@0.24.1
        |   `-- dateformat@1.0.12
        |     `-- meow@3.7.0
        |       `-- normalize-package-data@2.3.5
        |         `-- hosted-git-info@2.2.0
        +-- gulp-cli@1.2.2
        `-- yo@1.8.5
          `-- meow@3.7.0
            `-- normalize-package-data@2.3.5
              `-- hosted-git-info@2.2.0

    I read into your USAGE file four options :
        
        Options:
            Sass: Include Sass
            Bootstrap: Include Bootstrap or Bootstrap Sass if Sass is
        included
            Modernizr: Include Modernizr
            Babel: Use ES2015 features by using Babel
        
        But running yo webapp command, I can see ONLY tree options:
           _-----_
          |       |    .--------------------------.
          |--(o)--|    |  'Allo 'allo! Out of the |
         `---------´   |    box I include HTML5   |
          ( _´U`_ )    | Boilerplate, jQuery, and |
          /___A___\    | a gulpfile to build your |
           |  ~  |     |           app.           |
         __'.___.'__   '--------------------------'
           `  |° ´ Y `
        
        What more would you like? (Press <space> to se
        *) Sass
        *) Bootstrap
        *) Modernizr
        
        and not BAbel.
    I think I do not using the last version.

This is the version I was using:
npm ls -g generator-webapp
-- generator-webapp@2.4.0
        
        Can I download from npm the last version or not ?
    If not, how to test the latest version of your package ?
     
        Cheers,
    Claudio

**Comment by silvenon** [comment]
@clabnet I meant that you could apply that change to your generated `gulpfile.js`, but I just released [v2.4.1](https://github.com/yeoman/generator-webapp/releases/tag/v2.4.1) so you can update and try it that way too, whatever you want. 😉

**Comment by clabnet** [comment]
It seem to work, many thanks @silvenon.

**Comment by jpcmf** [comment]
After two days searching a solution, finally it seems to work, thank you @gkobilansky

**Comment by TheFutureJholler** [comment]
i am trying to run gulp local command in my terminal, can't get what's wrong... please help!

Aristotle:source iram$ gulp local
[12:40:16] Using gulpfile ~/projects/TestSCA/source/gulpfile.js
[12:40:16] Starting 'local'...
[12:40:16] Starting 'local-install'...
[12:40:16] Finished 'local-install' after 112 μs
...
...
...
+--------------------------------------------------------------+
+- Local http server available at:  http://localhost:7777/
+- Watching current folder:  /Users/iram/projects/TestSCA/source/Modules
+- To cancel Gulp Watch enter:  control + c
+--------------------------------------------------------------+
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:7777
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Aristotle:source iram$

**Comment by silvenon** [comment]
@TheFutureJholler you seem to have modified the project since you initially generated the code, so I don't know if I can help, but it looks like you already have a process running at port 7777. You can try running `npx kill-port 7777` and afterwards try `gulp local` again.
