### ISSUE TITLE
Error after run yo webapp

### ISSUE THREAD

**Issue by andreferreira-me** [yeoman/generator-webapp#628]
I tried to run `yo webapp` on a new vagrant Ubuntu 12.04 virtual machine and I received this error. Can anybody help me?

```
/usr/lib/node_modules/generator-webapp/node_modules/gulp-util/index.js:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/generator-webapp/node_modules/gulp-decompress/index.js:5:13)
    at Module._compile (module.js:570:32)
````

Versions:
Node: v6.9.5
NPM: 3.10.10
Gulp: CLI version 1.2.2
Yeoman: 1.8.5

**Comment by andreferreira-me** [comment]
I run `vagrant destroy` and after `vagrant up --provision` and it's all fine after that.

**Comment by andreferreira-me** [comment]
I run `vagrant destroy` and after `vagrant up --provision` and it's all fine after that.
