### ISSUE TITLE
Building dist throws error

### ISSUE THREAD

**Issue by partyparrotgreg** [yeoman/generator-webapp#634]
`gulp`
and then
```[19:36:03] Requiring external module babel-register
[19:36:04] Using gulpfile ~/Code/vakay-home/gulpfile.babel.js
[19:36:05] Starting 'clean'...
[19:36:05] Finished 'clean' after 30 ms
[19:36:05] Starting 'default'...
[19:36:05] Starting 'lint'...
[19:36:05] Starting 'styles'...
[19:36:05] Starting 'scripts'...
[19:36:05] Starting 'images'...
[19:36:06] Starting 'fonts'...
[19:36:06] Starting 'extras'...
[19:36:06] Finished 'default' after 1.11 s
[19:36:06] Finished 'lint' after 1.26 s
[19:36:06] Finished 'styles' after 1.4 s
[19:36:06] Finished 'scripts' after 1.07 s
[19:36:06] Starting 'html'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)
    at expression (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2875:20)
    at simple_statement (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:55)
    at eval (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2178:20)
    at eval (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at eval (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2904:23)
    at Object.parse (eval at <anonymous> (/Users/greg/Code/vakay-home/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2915:7)
```
any advice? 

-- Update --
I have disabled:

```gulp.task('html', ['styles', 'scripts'], () => {
  return gulp.src('app/*.html')
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    //.pipe($.if('*.js', $.uglify()))
    //.pipe($.if('*.css', $.cssnano()))
    //.pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
    .pipe(gulp.dest('dist'));
});
```
and it worked

**Comment by silvenon** [comment]
Update to the latest version of generator-webapp, or you can copy the fix from [here](https://github.com/yeoman/generator-webapp/blob/a55978316a4c545c3a9425e6ce2f9468756425e0/app/templates/gulpfile.js#L67-L69) (regexes instead of strings as first params to `$.if()`).
