### ISSUE TITLE
htmlmin doesn't work

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#651]
I'm not sure why htmlmin doesn't work. It also affect to css and js, they are not minified neither.

```
gulp.task('html', ['views','styles', 'scripts'], () => {
  return gulp.src(['app/*.html', '.tmp/*.html'])
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('/\.js$/', $.uglify({compress: {drop_console: true}})))
    .pipe($.if('/\.css$/b', $.cssnano({safe: true, autoprefixer: false})))
    .pipe($.if('/\.html$/', $.htmlmin({
      collapseWhitespace: true,
      minifyCSS: true,
      minifyJS: {compress: {drop_console: true}},
      processConditionalComments: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true 
    })))
    .pipe(gulp.dest('dist'));
});
```

I use Pug recipe btw.

**Comment by silvenon** [comment]
You can use [gulp-debug](https://github.com/sindresorhus/gulp-debug) to try to debug the issue. Check what's in the stream before `$.useref`.

**Comment by rizqinizamil** [comment]
I changed `/\.js$/` to `*.js` then it works. I changed for css and html as well.
I'm not sure it just happened to me or anyone else too.

**Comment by silvenon** [comment]
@rizqinizamil maybe because you put the regex in quotes? The `gulpfile.js` we generate doesn't have quotes.

**Comment by rizqinizamil** [comment]
@silvenon if I remove the quotes I got this error:
```
/Applications/XAMPP/xamppfiles/htdocs/yeoman-nunjuck/gulpfile.js:74
    .pipe($.if(/\.css$/b, $.cssnano({safe: true, autoprefixer: false})))
               ^
SyntaxError: Invalid regular expression flags
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:25:18)
```
