### ISSUE TITLE
Error on run gulp command

### ISSUE THREAD

**Issue by raisiqueira** [yeoman/generator-webapp#660]
```
Unhandled rejection Error: Corrupt JPEG data: premature end of data segment

    at Promise.all.then.arr (/home/rai/projetos/postoSertao/node_modules/execa/index.js:201:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by silvenon** [comment]
Hey, since this issue we've made a lot of changes, let me know if this is still an issue.
