### ISSUE TITLE
Error in style after gulp serve

### ISSUE THREAD

**Issue by johnreytanquinco** [yeoman/generator-webapp#664]
**Stats:**

> Node v6.10.2
> Npm v4.6.1
> Bower v1.8.0
> Yo v1.8.5
> Gulp cli v3.9.1

I have a fresh installed webapp in my custom directory. Everything works as expected until when I issue `$ gulp serve`, I got the error message below. It loads a browser link but only plain text.

```
johnreytanquinco@johnreytanquinco-macbookpro:~/upwork/bower$ gulp serve
[23:33:17] Using gulpfile ~/upwork/bower/gulpfile.js
[23:33:17] Starting 'serve'...
[23:33:17] Starting 'clean'...
[23:33:17] Starting 'wiredep'...
[23:33:17] Finished 'wiredep' after 128 ms
[23:33:17] Finished 'serve' after 148 ms
[23:33:17] Finished 'clean' after 156 ms
[23:33:17] Starting 'styles'...
[23:33:18] 'styles' errored after 752 ms
[23:33:18] Error: Missing binding /home/johnreytanquinco/upwork/bower/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/home/johnreytanquinco/upwork/bower/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/johnreytanquinco/upwork/bower/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/johnreytanquinco/upwork/bower/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:409:26)
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:9000
    External: http://192.168.254.101:9000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.254.101:3001
 ----------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: app
[23:33:19] Starting 'styles'...
[23:33:19] 'styles' errored after 5.88 ms
[23:33:19] Error: Missing binding /home/johnreytanquinco/upwork/bower/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/home/johnreytanquinco/upwork/bower/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/johnreytanquinco/upwork/bower/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/johnreytanquinco/upwork/bower/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:409:26)
```

I did what was suggested in my research to follow this commands but no luck.
```
npm rebuild node-sass
rm -rf node_modules
npm i
```

TIA

**Comment by neilhem** [comment]
Do you use node version managers?

**Comment by islishude** [comment]
try this 

`npm i -D gulp-sass@latest`

**Comment by islishude** [comment]
#669

**Comment by silvenon** [comment]
We update a lot of things in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0), so reopen the issue if the issue persists.
