### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by Yourdigitalheart** [yeoman/generator-webapp#702]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error: bootstrap is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/wiredep/wiredep.js:30:56
    at /Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/wiredep/lib/detect-dependencies.js:149:29
    at /Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/lodash/lodash.js:3001:24)
    at /Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/wiredep/wiredep.js:70:39)
    at module.exports.end (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/app/index.js:362:5)
    at Object.<anonymous> (/Users/bookpro/.nvm/versions/node/v8.9.1/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/index.js:417:23)

**Comment by muhamed87** [comment]
The bootstrap team is not going to use bower anymore, check this
https://github.com/twbs/bootstrap/issues/24963

**Comment by neilhem** [comment]
Yeah, bower is deprecated, so we should move to npm/yarn, but there are some blocking issues

**Comment by silvenon** [comment]
We removed Bower (and wiredep) in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0).
