### ISSUE TITLE
Finished 'wiredep' after 20 ms events.js:165   throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by matbrgz** [yeoman/generator-webapp#715]
turing@DESKTOP-TKI46T0:/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018$ gulp
[17:01:52] Using gulpfile /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/gulpfile.js
[17:01:52] Starting 'default'...
[17:01:52] Starting 'clean'...
[17:01:52] Starting 'wiredep'...
[17:01:52] Finished 'wiredep' after 21 ms
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:222:9)
    at new Buffer (buffer.js:170:17)
    at DestroyableTransform._transform (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:136:23)
    at DestroyableTransform.Transform._read (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at write (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:632:7)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:180:13)
    at DestroyableTransform._transform (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:138:12)
    at DestroyableTransform.Transform._read (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    [... lines matching original stack trace ...]
    at flow (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:632:7)
turing@DESKTOP-TKI46T0:/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018$ bower uninstall fontawesome
bower uninstall     fontawesome
turing@DESKTOP-TKI46T0:/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018$ gulp
[17:07:36] Using gulpfile /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/gulpfile.js
[17:07:36] Starting 'default'...
[17:07:36] Starting 'clean'...
[17:07:36] Starting 'wiredep'...
[17:07:36] Finished 'wiredep' after 20 ms
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Error: fontawesome is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:30:56
    at /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/lib/detect-dependencies.js:149:29
    at /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/lodash/lodash.js:3002:24)
    at /mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/lodash/lodash.js:9334:14)
    at detectDependencies (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:136:34)
    at DestroyableTransform.Transform._read (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:184:10)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:180:13)
    at DestroyableTransform._transform (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/wiredep/wiredep.js:138:12)
    at DestroyableTransform.Transform._read (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at StreamFilter.ondata (/mnt/d/Cloud/OneDrive/Dev/SACSIS2018/2018/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at StreamFilter.emit (events.js:180:13)
`
I try https://github.com/mcasimir/generator-mobileangularui/issues/8

`{
  "name": "acrab-sacsisx",
  "private": true,
  "dependencies": {
    "bootstrap-sass": "~3.3.5",
    "modernizr": "~2.8.1",
    "waypoints": "^4.0.1",
    "smoothscroll": "^0.4.2",
    "fontawesome": "^5.0.9",
    "counterup": "^1.0.0",
    "gmap3": "^7.2.0",
    "jquery-colorbox": "colorbox#^1.6.4",
    "animate.css": "^3.5.2",
    "html5shiv": "^3.7.3",
    "respond": "^1.4.2"
  },
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/*",
        "assets/javascripts/bootstrap.js"
      ]
    }
  }
}
`

`{
  "private": true,
  "engines": {
    "node": ">=4"
  },
  "devDependencies": {
    "babel-core": "^6.4.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-register": "^6.5.2",
    "browser-sync": "^2.2.1",
    "del": "^2.2.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.0.1",
    "gulp-babel": "^6.1.1",
    "gulp-cache": "^0.4.2",
    "gulp-cssnano": "^2.0.0",
    "gulp-eslint": "^3.0.0",
    "gulp-filter": "^4.0.0",
    "gulp-htmlmin": "^3.0.0",
    "gulp-if": "^2.0.2",
    "gulp-imagemin": "^3.0.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-plumber": "^1.0.1",
    "gulp-sass": "^3.0.0",
    "gulp-size": "^2.1.0",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-uglify": "^2.0.0",
    "gulp-useref": "^3.0.0",
    "main-bower-files": "^2.5.0",
    "run-sequence": "^1.2.2",
    "wiredep": "^4.0.0"
  },
  "eslintConfig": {
    "env": {
      "es6": true,
      "node": true,
      "browser": true
    },
    "rules": {
      "quotes": [
        2,
        "single"
      ]
    }
  },
  "dependencies": {
    "yarn": "^1.5.1"
  }
}
`

**Comment by silvenon** [comment]
We removed Bower (and wiredep) in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0).
