### ISSUE TITLE
Can't run 'styles' task

### ISSUE THREAD

**Issue by jonkemp** [yeoman/generator-webapp#86]
Trying to run `gulp styles` produces the following error. I am on Windows 7. I have the latest version of the generator.

``` bash
Syntax error: Undefined variable: "$alert-padding".
        on line 10 of C:/Documents/htdocs/gulp-webapp/app/styles/../bower_components/bootstrap-sass-
official/vendor/assets/stylesheets/bootstrap/_alerts.scss
        from line 5 of C:\Documents\htdocs\gulp-webapp\app\styles\main.scss
  Use --trace for backtrace.


events.js:72
        throw er; // Unhandled 'error' event
              ^
[←[32mgulp←[39m] Error in plugin '←[36mgulp-ruby-sass←[39m':
Syntax error: Undefined variable: "$alert-padding".
        on line 10 of C:/Documents/htdocs/gulp-webapp/app/styles/../bower_components/bootstrap-sass-
official/vendor/assets/stylesheets/bootstrap/_alerts.scss
        from line 5 of C:\Documents\htdocs\gulp-webapp\app\styles\main.scss
  Use --trace for backtrace.

    at ChildProcess.<anonymous> (C:\Documents\htdocs\gulp-webapp\node_modules\gulp-ruby-sass\index.j
s:100:25)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by mocon** [comment]
@andrantis thanks!
